
service: go-service

frameworkVersion: "2"

provider:
  name: aws
  region: eu-west-1
  runtime: go1.x
  stage: dev

package:
  exclude:
    - ./**
  include:
    - ./.bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
